### ISSUE TITLE
Different kind of link (email, torrent, tel)

### ISSUE THREAD

**Issue by HumanG33k** [az0/linkgopher#37]
This is about get all kind of link of a page.

for ie starting with :
 

- magnet:
- tel: 
- mailto:

**Comment by jadedgnome** [comment]
forum bbcode too
[MEDIA=youtube]e3spHrM7svg[/MEDIA]

**Comment by gitoss** [comment]
Linkgopher (with the old dual-coloured chain icon) used to extract magnet links, but now with the recent update it doesn't anymore. Please kindly re-add this feature, 

Sample magnet link: magnet:?xt=urn:btih:9F9165D9A281A9B8E782CD5176BBCC8256FD1871&dn=Ubuntu+16.04.1+LTS+Desktop+64-bit&tr=http%3A%2F%2Ftorrent.ubuntu.com%3A6969%2Fannounce&tr=http%3A%2F%2Fipv6.torrent.ubuntu.com%3A6969%2Fannounce

I'm not asking for special handling of numerous other possible link types - but just to not dumb down the extension and to restore this one feature.

**Comment by az0** [comment]
On Mozilla, I disabled Link Gopher version 2.6.1, which makes version 2.5.0 the primary version. I assume it will not downgrade you, so you may need to reinstall. Let me know how it goes.

**Comment by az0** [comment]
I released Link Gopher 2.6.2 to revert the theme-related changes. Better now?

**Comment by gitoss** [comment]
> I released Link Gopher 2.6.2 to revert the theme-related changes. Better now?

Um, Mozilla Addons still shows 2.5.0 "Last updated 25 days ago (Sep 28, 2023)" - can I get the xpi over here on github to give it a try?
